# Generated by Django 5.0.8 on 2026-02-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=64, unique=True)),
                ('secret_key', models.CharField(max_length=128)),
                ('name', models.CharField(default='Smart Light', max_length=100)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('cmd_sent', 'Command sent'), ('cmd_applied', 'Command applied'), ('schedule_triggered', 'Schedule triggered'), ('error', 'Error')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_events', to='api.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='api_logeven_device__126687_idx'), models.Index(fields=['event_type', 'timestamp'], name='api_logeven_event_t_66db97_idx')],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('voltage', models.FloatField(default=120)),
                ('current', models.FloatField()),
                ('power', models.FloatField(blank=True, null=True)),
                ('energy_total', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='api.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='api_powerre_device__94ed67_idx')],
                'unique_together': {('device', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('BRIGHTNESS', 'Set brightness')], max_length=16)),
                ('brightness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'start_time', 'enabled'], name='api_schedul_device__95fb26_idx')],
            },
        ),
    ]
